fix(circleci): change VM image for executor
Due to the failing build: https://circleci.com/gh/topheman/docker-experiments/2

```
ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
Exited with code 1
```

Reason:

Default circleci image doesn't support latest docker-compose file format (need docker-engine up-to-date)
Changed image used by VM in machine executor mode.

For the compatibility between docker-engine version and docker-compose file format, see https://docs.docker.com/compose/compose-file/#compose-and-docker-compatibility-matrix
For the list of available circleci images, see https://circleci.com/docs/2.0/configuration-reference/#machine

See readme: https://github.com/topheman/docker-experiments#how-to-use-latest-version-of-docker-compose--docker-engine